version: '3.9'
services:
  database:
    image: mcr.microsoft.com/mssql/server:2025-latest
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  backend:
    build:
      context: ./src
      dockerfile: /CarMechanicWorkshop.Api/Dockerfile
    depends_on:
      - database
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=database;Database=CarMechanicWorkshopDatabase;User=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True
      - FRONTEND_API=http://frontend
    ports:
      - "8080:8080"
      - "8443:8443"
    
  
  frontend:
    build:
      context: ./src
      dockerfile: /CarMechanicWorkshop.Client/Dockerfile
      args:
        BACKEND_API: http://backend:8080
    depends_on:
      - backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - BACKEND_API=http://backend:8080
    ports:
      - "80:80"
      - "443:443"

volumes:
  sql_data:
