using AutoMapper;
using CarMechanicWorkshop.Domain.Entities;
using CarMechanicWorkshop.Shared.DTOs.Clients;

namespace CarMechanicWorkshop.Application.Mappers;

/// <summary>
/// Defines AutoMapper configuration for mapping between Client-related entities and DTOs.
/// Handles creation, updating, and bi-directional mappings while ignoring non-modifiable fields.
/// </summary>
public class ClientProfile : Profile
{
    /// <summary>
    /// Initializes a new instance of the <see cref="ClientProfile"/> class
    /// and registers all mapping rules for Client entities and DTOs.
    /// </summary>
    public ClientProfile()
    {
        // -------------------------------------------------
        // Client ↔ ClientDTO (two-way mapping)
        // -------------------------------------------------
        /// <summary>
        /// Maps between <see cref="Client"/> and <see cref="ClientDTO"/>.
        /// ReverseMap() enables mapping in both directions.
        /// </summary>
        CreateMap<Client, ClientDTO>().ReverseMap();

        // -------------------------------------------------
        // CreateClientDTO → Client
        // -------------------------------------------------
        /// <summary>
        /// Mapping for creating a new client entity.
        /// The database ID and navigation properties are ignored because they are generated by the system.
        /// </summary>
        CreateMap<CreateClientDTO, Client>()
            .ForMember(dest => dest.Id, opt => opt.Ignore())
            .ForMember(dest => dest.Jobs, opt => opt.Ignore());

        // -------------------------------------------------
        // UpdateClientDTO → Client
        // -------------------------------------------------
        /// <summary>
        /// Mapping for updating an existing client entity.
        /// Only non-null source values are applied (patch behavior).
        /// ID and Jobs are ignored because they cannot be updated externally.
        /// </summary>
        CreateMap<UpdateClientDTO, Client>()
            .ForMember(dest => dest.Id, opt => opt.Ignore())
            .ForMember(dest => dest.Jobs, opt => opt.Ignore())
            .ForAllMembers(opt =>
                opt.Condition((src, dest, srcMember) => srcMember != null));
    }
}